### ISSUE TITLE
Remove prev_tax return if state check

### ISSUE THREAD

**Issue by ericsaupe** [boomerdigital/solidus_avatax_certified#31]
On this line here https://github.com/boomerdigital/solidus_avatax_certified/blob/master/app/models/spree/calculator/avalara_transaction.rb#L17 you are checking if the order is in the address or the cart state. But solidus computes taxes on transitions from the address step. This is causing issues in the admin where the taxes are not getting calculated until _after_ a payment is added.

Is there any reason to have this line? I think it should be removed so that the solidus state machine transitions are respected for creating taxes.

Address transiton (this is broken using Avatax certified): https://github.com/solidusio/solidus/blob/v1.3/core/app/models/spree/order/checkout.rb#L93
Payment transition:
https://github.com/solidusio/solidus/blob/v1.3/core/app/models/spree/order/checkout.rb#L81

**Comment by acreilly** [comment]
Taxes are being calculated before a payment has been captured, taxes are not being committed until a payment has been captured. This is because once a payment is captured, you cannot adjust the order, tax will not recalculate, it will cause errors. 

The reason why we have that line is to wait to hit the api until we have all the necessary information. Each API call costs and we have had complaints from users of the spree_avatax_certified gem that too many api calls are occurring.

**Comment by ericsaupe** [comment]
We are still seeing an issue where creating an order using the admin interface causes the payment created to have the incorrect amount. What is the fix for that then?

**Comment by acreilly** [comment]
Hm, interesting. Haven't tested it that way. I am open to suggestions on that. Maybe have a button to click under the adjustments tab called calculate tax?

**Comment by ericsaupe** [comment]
I think we may have solved this another way by transitioning the order from the delivery to the payment step when the admin user clicks payment.
