### ISSUE TITLE
avalara_response[:totalTax] is always nil

### ISSUE THREAD

**Issue by prwhitehead** [boomerdigital/solidus_avatax_certified#96]
The conditional `return 0 if avalara_response[:totalTax] == 0.0`, but not as intended, as `avalara_response[:totalTax]` always returns `nil` because it will not be found in the hash.

Should be... 

    module Spree
      class Calculator::AvalaraTransaction < Calculator::DefaultTax
        # ...

        def tax_for_item(item, avalara_response)
          prev_tax_amount = prev_tax_amount(item)

          return prev_tax_amount if avalara_response.nil?
          return 0 if avalara_response['totalTax'] == 0.0

          avalara_response['lines'].each do |line|
            if line['lineNumber'] == "#{item.id}-#{item.avatax_line_code}"
              return line['taxCalculated']
            end
          end
          0
        end
      end
    end

**Comment by acreilly** [comment]
@prwhitehead Which branch are you working off of?

The reasoning behind this is because if either tax calculation or document committing are set to false:
https://github.com/boomerdigital/solidus_avatax_certified/blob/master/app/models/spree/avalara_transaction.rb#L21

Or if an error arises:
https://github.com/boomerdigital/solidus_avatax_certified/blob/master/app/models/spree/avalara_transaction.rb#L63

We want a quick way to return 0 since there will be no avalara_response['lines']

If avalara_response[:totalTax] is not found in the hash, then that is because it has calculated properly.
@dhonig thoughts?

**Comment by dhonig** [comment]
@jasonfb @acreilly  maybe check for this condition and set a sensible default?

**Comment by prwhitehead** [comment]
@acreilly sorry I dont think I explained as well as I could. The hash is not set `with_indifferent_access`, so `avalara_response[:totalTax]` will always return `nil` as the key is `(string) "totalTax" ` not `(symbol) :totalTax`.

**Comment by acreilly** [comment]
https://github.com/boomerdigital/solidus_avatax_certified/pull/113
